// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfeyZ5_TKv-03AxCtoz-6AjF2IjOjmU0E',
    appId: '1:935255512324:web:7a4c6b7dbca4bcec3eac51',
    messagingSenderId: '935255512324',
    projectId: 'crudflutter-b5485',
    authDomain: 'crudflutter-b5485.firebaseapp.com',
    storageBucket: 'crudflutter-b5485.firebasestorage.app',
    measurementId: 'G-J3CK5Y480X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBztmucwTbXNJy18HWPjwOcxqctdj6eJ9s',
    appId: '1:935255512324:android:aabb971848ed268c3eac51',
    messagingSenderId: '935255512324',
    projectId: 'crudflutter-b5485',
    storageBucket: 'crudflutter-b5485.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL_imIcDZ87JH2licztKAxnRvvHtloRtc',
    appId: '1:935255512324:ios:8b1388d3f9ae25763eac51',
    messagingSenderId: '935255512324',
    projectId: 'crudflutter-b5485',
    storageBucket: 'crudflutter-b5485.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFlutter',
  );
}
